import { Outfit, Young_Serif } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ['400', '600', '700'],
  variable: '--text-font'
});
const youngSerif = Young_Serif({
  subsets: ["latin"],
  weight: ['400'],
  variable: '--head-font'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"className={`${outfit.variable} ${youngSerif.variable}`}>
      <body>{children}</body>
    </html>
  );
}
